/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UIRequest;
import java.io.File;
import java.io.FileFilter;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class FrRequest extends javax.swing.JFrame {

    public JComboBox<String> getCbcategory() {
        return cbcategory;
    }

    public void setCbcategory(JComboBox<String> cbcategory) {
        this.cbcategory = cbcategory;
    }

    public JComboBox<String> getCbcourse() {
        return cbcourse;
    }

    public void setCbcourse(JComboBox<String> cbcourse) {
        this.cbcourse = cbcourse;
    }

    public JComboBox<String> getCbgroup() {
        return cbgroup;
    }

    public void setCbgroup(JComboBox<String> cbgroup) {
        this.cbgroup = cbgroup;
    }

    public JLabel getLbNameCourse() {
        return lbNameCourse;
    }

    public void setLbNameCourse(JLabel lbNameCourse) {
        this.lbNameCourse = lbNameCourse;
    }

    public JTextField getTxtcarne() {
        return txtcarne;
    }

    public void setTxtcarne(JTextField txtcarne) {
        this.txtcarne = txtcarne;
    }

    public JTextArea getTxtdescription() {
        return txtdescription;
    }

    public void setTxtdescription(JTextArea txtdescription) {
        this.txtdescription = txtdescription;
    }

    public JTextField getTxtemail() {
        return txtemail;
    }

    public void setTxtemail(JTextField txtemail) {
        this.txtemail = txtemail;
    }

    public JTextField getTxtname() {
        return txtname;
    }

    public void setTxtname(JTextField txtname) {
        this.txtname = txtname;
    }

    public JComboBox<String> getCbperiod() {
        return cbperiod;
    }

    public void setCbperiod(JComboBox<String> cbperiod) {
        this.cbperiod = cbperiod;
    }

    public JTextField getTxtphone() {
        return txtphone;
    }

    /**
     * Creates new form FrRequest
     */
    public void setTxtphone(JTextField txtphone) {
        this.txtphone = txtphone;
    }

    
    private UIRequest uiRequest; 
    public FrRequest() {
        uiRequest=new UIRequest();
        initComponents();
        uiRequest.setallPeriods(this);
        cbperiod.setSelectedIndex(0);
        uiRequest.setallCourses(this);
        cbcourse.setSelectedIndex(0);
        uiRequest.setallGroups(this);
        cbgroup.setSelectedIndex(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtcarne = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbcategory = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnAddFile = new javax.swing.JButton();
        cbgroup = new javax.swing.JComboBox<>();
        cbcourse = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescription = new javax.swing.JTextArea();
        lbNameCourse = new javax.swing.JLabel();
        cbperiod = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnNewRequest = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnViewRequest = new javax.swing.JMenuItem();
        btnviewStadistics = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel1.setText("Carné");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        txtcarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcarneActionPerformed(evt);
            }
        });
        getContentPane().add(txtcarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 233, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 20));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 233, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel3.setText("Correo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 174, -1, 30));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 233, 20));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel4.setText("Teléfono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 20));

        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 233, 20));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel5.setText("Periodo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, 20));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel6.setText("Curso");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel7.setText("Grupo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, 20));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel8.setText("Categoría");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, 20));

        cbcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ERROR_NOTA", "EXCLUSION_ACTA", "INCLUSION_ACTA" }));
        cbcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcategoryActionPerformed(evt);
            }
        });
        getContentPane().add(cbcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 280, 20));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel9.setText("Información Básica del Estudiante ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 280, -1));

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel10.setText("Información del Problema");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, -1));

        btnOK.setText("Aceptar");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, -1, -1));

        btnAddFile.setText("Agregar Archivo ");
        btnAddFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFileActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, -1, 20));

        cbgroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgroupActionPerformed(evt);
            }
        });
        getContentPane().add(cbgroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 280, -1));

        cbcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcourseActionPerformed(evt);
            }
        });
        getContentPane().add(cbcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 80, -1));

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel12.setText("Descripción");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 23));

        txtdescription.setColumns(20);
        txtdescription.setRows(5);
        jScrollPane1.setViewportView(txtdescription);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 900, -1));
        getContentPane().add(lbNameCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 190, 20));

        cbperiod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbperiodActionPerformed(evt);
            }
        });
        getContentPane().add(cbperiod, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 280, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/images/5193848-white-wallpaper.jpg"))); // NOI18N
        jLabel33.setText("jLabel2");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 480));

        jMenu1.setText("Archivo");

        btnNewRequest.setText("Nueva Solicitud...");
        btnNewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRequestActionPerformed(evt);
            }
        });
        jMenu1.add(btnNewRequest);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ver ");

        btnViewRequest.setText("Ver Solicitudes");
        btnViewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestActionPerformed(evt);
            }
        });
        jMenu2.add(btnViewRequest);

        btnviewStadistics.setText("Ver Estadísticas");
        btnviewStadistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewStadisticsActionPerformed(evt);
            }
        });
        jMenu2.add(btnviewStadistics);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRequestActionPerformed
        // TODO add your handling code here:
        txtcarne.setText("");
        txtdescription.setText("");
        txtemail.setText("");
        txtname.setText("");
        txtphone.setText("");
                    
                
    }//GEN-LAST:event_btnNewRequestActionPerformed

    private void txtcarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcarneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcarneActionPerformed

    private void cbcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcategoryActionPerformed

    private void btnAddFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFileActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc= new JFileChooser();
        jfc.showOpenDialog(null);
        File f=jfc.getSelectedFile();
        String filename= f.getAbsolutePath();
    }//GEN-LAST:event_btnAddFileActionPerformed

    private void btnViewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestActionPerformed
        // TODO add your handling code here:
        FrViewRequest fvr=new FrViewRequest();
        this.setVisible(false);
        fvr.setVisible(true);
    }//GEN-LAST:event_btnViewRequestActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        
    
       
        uiRequest.createRequest(this);
        
        
        
    }//GEN-LAST:event_btnOKActionPerformed

    private void cbcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcourseActionPerformed
        // TODO add your handling code here:
         uiRequest.setallGroups(this);
         cbgroup.setSelectedIndex(0);
    }//GEN-LAST:event_cbcourseActionPerformed

    private void btnviewStadisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewStadisticsActionPerformed
        // TODO add your handling code here:
        FrStadistics frstadistics= new FrStadistics();
        frstadistics.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnviewStadisticsActionPerformed

    private void cbperiodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbperiodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbperiodActionPerformed

    private void cbgroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbgroupActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFile;
    private javax.swing.JMenuItem btnNewRequest;
    private javax.swing.JButton btnOK;
    private javax.swing.JMenuItem btnViewRequest;
    private javax.swing.JMenuItem btnviewStadistics;
    private javax.swing.JComboBox<String> cbcategory;
    private javax.swing.JComboBox<String> cbcourse;
    private javax.swing.JComboBox<String> cbgroup;
    private javax.swing.JComboBox<String> cbperiod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNameCourse;
    private javax.swing.JTextField txtcarne;
    private javax.swing.JTextArea txtdescription;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
