/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UIRequest;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author Ximena
 */
public class FrViewRequest extends javax.swing.JFrame {
    private UIRequest uiRequest;
    /**
     * Creates new form FrViewRequest
     */
    public FrViewRequest() {
        uiRequest=new UIRequest();
        initComponents();
        uiRequest.setallRequest(this);
        
    }

    public JComboBox<String> getCdRequest() {
        return cdRequest;
    }

    public void setCdRequest(JComboBox<String> cdRequest) {
        this.cdRequest = cdRequest;
    }

    public JLabel getLbCategory() {
        return lbCategory;
    }

    public void setLbCategory(JLabel lbCategory) {
        this.lbCategory = lbCategory;
    }

    public JLabel getLbcarne() {
        return lbcarne;
    }

    public void setLbcarne(JLabel lbcarne) {
        this.lbcarne = lbcarne;
    }

    public JLabel getLbcourse() {
        return lbcourse;
    }

    public void setLbcourse(JLabel lbcourse) {
        this.lbcourse = lbcourse;
    }

    public JLabel getLbdescription() {
        return lbdescription;
    }

    public void setLbdescription(JLabel lbdescription) {
        this.lbdescription = lbdescription;
    }

    public JLabel getLbemail() {
        return lbemail;
    }

    public void setLbemail(JLabel lbemail) {
        this.lbemail = lbemail;
    }

    public JLabel getLbgroup() {
        return lbgroup;
    }

    public void setLbgroup(JLabel lbgroup) {
        this.lbgroup = lbgroup;
    }

    public JLabel getLbname() {
        return lbname;
    }

    public void setLbname(JLabel lbname) {
        this.lbname = lbname;
    }

    public JLabel getLbperiod() {
        return lbperiod;
    }

    public void setLbperiod(JLabel lbperiod) {
        this.lbperiod = lbperiod;
    }

    public JLabel getLbphone() {
        return lbphone;
    }

    public void setLbphone(JLabel lbphone) {
        this.lbphone = lbphone;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrViewRequest = new javax.swing.JFrame();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        btnCancelRequest = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        btnNewRequest = new javax.swing.JMenuItem();
        btnNewResolution = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnViewRequest = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        lbcarne = new javax.swing.JLabel();
        lbperiod = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lbdescription = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        lbCategory = new javax.swing.JLabel();
        lbphone = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        lbgroup = new javax.swing.JLabel();
        lbcourse = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        lbemail = new javax.swing.JLabel();
        btnCancelRequest1 = new javax.swing.JButton();
        cdRequest = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        btnNewRequest1 = new javax.swing.JMenuItem();
        btnNewResolution1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        btnViewRequest1 = new javax.swing.JMenuItem();
        btnviewStadistics = new javax.swing.JMenuItem();

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Solicitud");

        jLabel13.setText("Periodo");

        jLabel14.setText("Carné");

        jLabel15.setText("Curso");

        jLabel16.setText("Grupo");

        jLabel17.setText("Nombre");

        jLabel18.setText("Descripción");

        jLabel19.setText("Categoría");

        jLabel20.setText("Correo");

        jLabel21.setText("Información Básica del Estudiante Afectado");

        jLabel22.setText("Teléfono");

        jLabel23.setText("Información del Problema");

        jLabel24.setText("#########################");

        jLabel25.setText("#########################");

        jLabel26.setText("#########################");

        jLabel27.setText("#########################");

        jLabel28.setText("#########################");

        jLabel29.setText("#########################");

        jLabel30.setText("#########################");

        jLabel31.setText("#########################");

        jLabel32.setText("#########################");

        btnCancelRequest.setText("Cancelar Solicitud ");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jMenu3.setText("Archivo");

        btnNewRequest.setText("Nueva Solicitud...");
        btnNewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRequestActionPerformed(evt);
            }
        });
        jMenu3.add(btnNewRequest);

        btnNewResolution.setText("Nueva Resolución...");
        btnNewResolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewResolutionActionPerformed(evt);
            }
        });
        jMenu3.add(btnNewResolution);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Ver ");

        btnViewRequest.setText("Ver Solicitudes");
        jMenu4.add(btnViewRequest);

        jMenuBar2.add(jMenu4);

        FrViewRequest.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout FrViewRequestLayout = new javax.swing.GroupLayout(FrViewRequest.getContentPane());
        FrViewRequest.getContentPane().setLayout(FrViewRequestLayout);
        FrViewRequestLayout.setHorizontalGroup(
            FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrViewRequestLayout.createSequentialGroup()
                .addGroup(FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FrViewRequestLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FrViewRequestLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FrViewRequestLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrViewRequestLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                                .addComponent(jLabel29))
                            .addGroup(FrViewRequestLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel31))
                            .addGroup(FrViewRequestLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel30))
                            .addGroup(FrViewRequestLayout.createSequentialGroup()
                                .addGroup(FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel28))))
                    .addGroup(FrViewRequestLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32)
                            .addComponent(btnCancelRequest))))
                .addGap(89, 89, 89))
            .addGroup(FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FrViewRequestLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FrViewRequestLayout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                            .addComponent(jLabel23)
                            .addGap(115, 115, 115))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrViewRequestLayout.createSequentialGroup()
                            .addGroup(FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel14)
                                .addComponent(jLabel20)
                                .addComponent(jLabel22))
                            .addGap(369, 369, 369)
                            .addGroup(FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16)
                                .addComponent(jLabel19)
                                .addComponent(jLabel18))
                            .addGap(0, 0, Short.MAX_VALUE)))))
        );
        FrViewRequestLayout.setVerticalGroup(
            FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrViewRequestLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FrViewRequestLayout.createSequentialGroup()
                        .addGroup(FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addComponent(jLabel24)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18))
                    .addGroup(FrViewRequestLayout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addGap(27, 27, 27)))
                .addGroup(FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel30))
                .addGroup(FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrViewRequestLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel27)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrViewRequestLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addGap(33, 33, 33)))
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnCancelRequest)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FrViewRequestLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addGroup(FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel21))
                    .addGroup(FrViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FrViewRequestLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jLabel14)
                            .addGap(24, 24, 24)
                            .addComponent(jLabel17)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel20)
                            .addGap(29, 29, 29)
                            .addComponent(jLabel22))
                        .addGroup(FrViewRequestLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel16)
                            .addGap(25, 25, 25)
                            .addComponent(jLabel15)
                            .addGap(27, 27, 27)
                            .addComponent(jLabel13)
                            .addGap(29, 29, 29)
                            .addComponent(jLabel19)
                            .addGap(30, 30, 30)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(193, Short.MAX_VALUE)))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/images/5193848-white-wallpaper.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbcarne.setText("#########################");
        getContentPane().add(lbcarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        lbperiod.setText("#########################");
        getContentPane().add(lbperiod, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));

        jLabel35.setText("Información Básica del Estudiante Afectado");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, 30));

        lbname.setText("#########################");
        getContentPane().add(lbname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel12.setText("Solicitud");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        jLabel37.setText("Teléfono");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel38.setText("Grupo");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, -1));

        jLabel39.setText("Descripción");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        jLabel40.setText("Curso");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, -1));

        lbdescription.setText("#########################");
        getContentPane().add(lbdescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, -1, -1));

        jLabel42.setText("Periodo");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 308, 820, -1));

        jLabel43.setText("Información del Problema");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, -1, 30));

        jLabel44.setText("Correo");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel45.setText("Carné");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        lbCategory.setText("ERROR_NOTA");
        getContentPane().add(lbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, -1, -1));

        lbphone.setText("#########################");
        getContentPane().add(lbphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel48.setText("Categoría");
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        lbgroup.setText("#########################");
        getContentPane().add(lbgroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, -1, -1));

        lbcourse.setText("#########################");
        getContentPane().add(lbcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, -1, -1));

        jLabel51.setText("Nombre");
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        lbemail.setText("#########################");
        getContentPane().add(lbemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        btnCancelRequest1.setText("Cancelar Solicitud ");
        getContentPane().add(btnCancelRequest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, -1, -1));

        cdRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdRequestActionPerformed(evt);
            }
        });
        getContentPane().add(cdRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 200, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/images/5193848-white-wallpaper.jpg"))); // NOI18N
        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 490));

        jMenu5.setText("Archivo");

        btnNewRequest1.setText("Nueva Solicitud...");
        btnNewRequest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRequest1ActionPerformed(evt);
            }
        });
        jMenu5.add(btnNewRequest1);

        btnNewResolution1.setText("Nueva Resolución...");
        btnNewResolution1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewResolution1ActionPerformed(evt);
            }
        });
        jMenu5.add(btnNewResolution1);

        jMenuBar3.add(jMenu5);

        jMenu6.setText("Ver ");

        btnViewRequest1.setText("Ver Solicitudes");
        jMenu6.add(btnViewRequest1);

        btnviewStadistics.setText("Ver Estadísticas");
        btnviewStadistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewStadisticsActionPerformed(evt);
            }
        });
        jMenu6.add(btnviewStadistics);

        jMenuBar3.add(jMenu6);

        setJMenuBar(jMenuBar3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRequestActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnNewRequestActionPerformed

    private void btnNewResolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewResolutionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnNewResolutionActionPerformed

    private void btnNewRequest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRequest1ActionPerformed
        // TODO add your handling code here:
        FrRequest fr=new FrRequest();
        fr.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnNewRequest1ActionPerformed

    private void btnNewResolution1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewResolution1ActionPerformed
        // TODO add your handling code here:
        FrResolution fr=new FrResolution();
        fr.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnNewResolution1ActionPerformed

    private void btnviewStadisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewStadisticsActionPerformed
        // TODO add your handling code here:
        FrStadistics frstadistics= new FrStadistics();
        frstadistics.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnviewStadisticsActionPerformed

    private void cdRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdRequestActionPerformed
        // TODO add your handling code here:
        uiRequest.setRequest(this);
    }//GEN-LAST:event_cdRequestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrViewRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrViewRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrViewRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrViewRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrViewRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrViewRequest;
    private javax.swing.JButton btnCancelRequest;
    private javax.swing.JButton btnCancelRequest1;
    private javax.swing.JMenuItem btnNewRequest;
    private javax.swing.JMenuItem btnNewRequest1;
    private javax.swing.JMenuItem btnNewResolution;
    private javax.swing.JMenuItem btnNewResolution1;
    private javax.swing.JMenuItem btnViewRequest;
    private javax.swing.JMenuItem btnViewRequest1;
    private javax.swing.JMenuItem btnviewStadistics;
    private javax.swing.JComboBox<String> cdRequest;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel lbCategory;
    private javax.swing.JLabel lbcarne;
    private javax.swing.JLabel lbcourse;
    private javax.swing.JLabel lbdescription;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbgroup;
    private javax.swing.JLabel lbname;
    private javax.swing.JLabel lbperiod;
    private javax.swing.JLabel lbphone;
    // End of variables declaration//GEN-END:variables
}
